server:
  port: 9101
spring:
  application:
    name: config-center-server
  cloud:
    config:
      server:
        git:
          uri:
          search-paths:  
eureka:
  client:
    service-url:
        defaultZone: http://peer1:9091/eureka/
    fetch-registry: false
