server:
  port: 9103
spring:
  application:
    name: microservice-user-center
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: root
      password: root
      database: db_user_center
eureka:
  client:
    service-url:
        defaultZone: http://peer1:9091/eureka/