spring:
  application:
    name: eureka-registry-center
server:
  port: 9092
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
         defaultZone: http://peer1:9091/eureka/
  instance:
    hostname: peer2
